Bump sass-loader to 10.2.0
We were seeing errors like

    Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.

and according to
https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0/64626556#64626556
this error comes from sass-loader. There is a semantic versioning
mismatch since node-sass @latest is v5.0.0 and sass-loader expects
^4.0.0.