Lock Webpack(er) to versions before v4
It seems like we might not be entirely ready to upgrade to Webpack 4 just yet.

We've been seeing errors like

     Failure/Error: = javascript_pack_tag "scripts/application"

     ActionView::Template::Error:
       Webpacker can't find scripts/application in /home/circleci/repo/public/packs-test/manifest.json. Possible causes:
       1. You want to set webpacker.yml value of compile to true for your environment
          unless you are using the `webpack -w` or the webpack-dev-server.
       2. webpack has not yet re-run to reflect updates.
       3. You have misconfigured Webpacker's config/webpacker.yml file.
       4. Your webpack configuration is not creating a manifest.
       Your manifest contains:
       {
       }

on CI, and attempts at fixing it seems to tumble us further down the rabbithole:

    $ rake assets:precompile                                                                                                                         rails6|●1✚5…
    yarn install v1.17.3
    [1/4] 🔍  Resolving packages...
    success Already up-to-date.
    ✨  Done in 0.54s.
    Compiling…
    Compilation failed:
    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration.entry should be an non-empty object.
       -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.

... and ...

    warning Integrity check: Top level patterns don't match
    error Integrity check failed
    error Found 1 errors.

without being able to install packages...