Make rake assets:precompile work
Sass is apparently required by Sprockets. Without it we get

    $ rake assets:precompile
    rake aborted!
    LoadError: cannot load such file -- sass
    /Users/jakob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
    /Users/jakob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
    /Users/jakob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
    /Users/jakob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
    /Users/jakob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.1/lib/sprockets/autoload/sass.rb:1:in `<top (required)>'